version: "3"
services:
  site:
    command: jekyll serve --watch --drafts
    image: jekyll/jekyll:latest
    volumes:
      # your path here
      - D:\site\github\Beats0.github.io:/srv/jekyll
    ports:
      - 4000:4000
      - 35729:35729
      - 3000:3000
      -   80:4000
    # environment:
    #   - jekyll build